import torch

def init():
    global PARAM
    PARAM = {
        'model_data_name': 'SVHN',
        'train_data_name': 'SVHN',
        'test_data_name': 'SVHN',
        'model_dir': 'mnist',
        'model_name': 'testnet_2',
        'resume_TAG': '',
        'special_TAG': '',
        'optimizer_name': 'Adam',
        'scheduler_name': 'ReduceLROnPlateau',
        'milestones': [10,20,50,100],
        'threshold': 1e-3,
        'threshold_mode': 'abs',
        'factor': 0.5,
        'normalize': False,
        'branch': False,
        'balance': False,
        'batch_size': [50,500],
        'num_workers': 0,
        'data_size': 0,
        'device': 'cuda',
        'max_num_epochs': 200,
        'save_mode': 0,
        'world_size': 1,
        'train_metric_names': ['psnr'],
        'test_metric_names': ['bpp','roc'],
        'topk': 1,
        'init_seed': 0,
        'num_Experiments': 1,
        'tuning_param': {'compression': 1, 'classification': 1},
        'loss_mode': {'compression':'mae','classification':'ce'},
        'code_size': 8*3,
        'cell_name': 'BasicCell',
        'num_iter': 16,
        'max_depth': 3,
        'patch_shape': (32,32),
        'step': [1.0,1.0],
        'jump_rate': 2,
        'train_num_node': 2,
        'test_num_node': 2,
        'resume_mode': 0
    }